apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: txajukd6q-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: txajukd6q-go 
  name: txajukd6q-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: txajukd6q-go 
